# Generated by Django 4.1.5 on 2023-01-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finanzas_Personales', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null='True', upload_to='posteos'),
            preserve_default='True',
        ),
    ]
